context:
  version: "17.13.0"

package:
  name: stylelint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/stylelint/-/stylelint-${{ version }}.tgz
  sha256: bfb181aaaaca1f5f37b221c1c518bfb7702c474a4380360ef51fae315c80d3b6

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - stylelint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A mighty CSS linter that helps you avoid errors and enforce conventions.
  homepage: https://github.com/stylelint/stylelint
  repository: https://github.com/stylelint/stylelint

extra:
  recipe-maintainers:
    - danielnachun
