context:
  version: 16.8.1

package:
  name: stylelint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/stylelint/-/stylelint-${{ version }}.tgz
  sha256: 037fc1198af5f004966747d41a8c7959aecccb04ec7ecce5f4b9048c2c2ef902

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - stylelint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A mighty CSS linter that helps you avoid errors and enforce conventions.
  homepage: https://github.com/stylelint/stylelint
  repository: https://github.com/stylelint/stylelint

extra:
  recipe-maintainers:
    - danielnachun
