context:
  version: "16.14.1"

package:
  name: stylelint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/stylelint/-/stylelint-${{ version }}.tgz
  sha256: 4984085a54dc0ea761eb7024da8b2c01bfa964720ec7cc1115abfa140cb6f1d2

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - stylelint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A mighty CSS linter that helps you avoid errors and enforce conventions.
  homepage: https://github.com/stylelint/stylelint
  repository: https://github.com/stylelint/stylelint

extra:
  recipe-maintainers:
    - danielnachun
