context:
  version: "17.6.0"

package:
  name: stylelint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/stylelint/-/stylelint-${{ version }}.tgz
  sha256: 306f50de78b9dea42f52e21fe84a360cd2b23883e9bc093c548e6d37c846997c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - stylelint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A mighty CSS linter that helps you avoid errors and enforce conventions.
  homepage: https://github.com/stylelint/stylelint
  repository: https://github.com/stylelint/stylelint

extra:
  recipe-maintainers:
    - danielnachun
