context:
  version: "17.2.0"

package:
  name: stylelint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/stylelint/-/stylelint-${{ version }}.tgz
  sha256: 24dfa7c14ffd40e5114dc700f37a2d22b568b2470a0063166c40835c2e0e2015

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - stylelint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A mighty CSS linter that helps you avoid errors and enforce conventions.
  homepage: https://github.com/stylelint/stylelint
  repository: https://github.com/stylelint/stylelint

extra:
  recipe-maintainers:
    - danielnachun
